language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
script:
  - yarn build
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
  - yarn build-example
  - yarn deploy-example
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
